modLoader="javafml"
loaderVersion="[47,)"
license="Public Domain"

[[mods]]
modId="trueheal"
version="2.0.247.3.0"
displayName="True Healing"
updateJSONURL="https://github.com/Drakkxs/True-Healing/blob/2.0.0-47.3.0-forge-1.20.1/update.json"
displayURL="https://github.com/Drakkxs/True-Healing"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Drakkxs, MCreator"
description="Mobs heal after they're hurt using a custom potion effect."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.trueheal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration