modLoader="javafml"
loaderVersion="[4,)"
license="Public Domain"

[[mods]]
modId="trueheal"
version="2.0.147.3.0"
displayName="True Healing"
updateJSONURL="https://github.com/Drakkxs/True-Healing/blob/2.0.0-47.3.0-forge-1.20.1/update.json"
displayURL="https://github.com/Drakkxs/True-Healing"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Drakkxs, MCreator"
description="Mobs heal after they're hurt using a custom potion effect."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.trueheal]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.trueheal]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration